name = "lenient_parse"
version = "1.2.0"

description = "Lenient Python-like parsing functions for Gleam."
licences = ["Apache-2.0"]
repository = { type = "github", user = "JosephTLyons", repo = "lenient_parse" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
startest = ">= 0.5.0 and < 1.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
shellout = ">= 1.6.0 and < 2.0.0"
