name = "lenient_parse"
version = "2.0.0"

description = "Lenient parsing functions for Gleam, modeled after Python's `int()` and `float()` built-ins."
licences = ["Apache-2.0"]
repository = { type = "github", user = "JosephTLyons", repo = "lenient_parse" }

[dependencies]
bigi = ">= 3.2.0 and < 4.0.0"
gleam_deque = ">= 1.0.0 and < 2.0.0"
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleam_json = ">= 1.0.1 and < 2.0.0"
shellout = ">= 1.6.0 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
startest = ">= 0.5.0 and < 1.0.0"
